pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    def branchName = 'main'
                    git credentialsId: 'github', url: 'https://github.com/cobidex/messaging_app.git', branch: branchName

                    // Verify the branch
                    sh 'git branch'
                }
            }
        }

        stage('Set Up Python Environment') {
            steps {
                sh 'python3 -m venv venv'
                sh 'source venv/bin/activate'
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'source venv/bin/activate && pytest --junitxml=report.xml'
            }
        }

        stage('Publish Test Report') {
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
